# Phoenix SDR - Build Script (MinGW/GCC)
# Builds simple_am_receiver and waterfall tools

param(
    [switch]$Clean,
    [switch]$Release,
    [ValidateSet("major", "minor", "patch")]
    [string]$Increment
)

$ErrorActionPreference = "Stop"

# Configuration
$ProjectName = "phoenix_sdr"
$SrcDir = "src"
$IncludeDir = "include"
$BuildDir = "build"
$BinDir = "bin"
$VersionFile = "$IncludeDir\version.h"

# SDRplay API paths
$SDRplayInclude = "C:\Program Files\SDRplay\API\inc"
$SDRplayLib = "C:\Program Files\SDRplay\API\x64"

# SDL2 paths
$SDL2Dir = "$PSScriptRoot\libs\SDL2\SDL2-2.30.9\x86_64-w64-mingw32"
$SDL2Include = "$SDL2Dir\include\SDL2"
$SDL2Lib = "$SDL2Dir\lib"

# Compiler (MinGW/GCC via winget)
$MinGWBin = "$env:LOCALAPPDATA\Microsoft\WinGet\Packages\BrechtSanders.WinLibs.POSIX.UCRT_Microsoft.Winget.Source_8wekyb3d8bbwe\mingw64\bin"
$CC = "$MinGWBin\gcc.exe"

function Write-Status($msg) {
    Write-Host "[$ProjectName] " -ForegroundColor Cyan -NoNewline
    Write-Host $msg
}

#============================================================================
# Version Management
#============================================================================

function Get-GitCommit {
    try {
        $commit = git rev-parse --short HEAD 2>$null
        if ($LASTEXITCODE -eq 0) { return $commit.Trim() }
    } catch { }
    return "unknown"
}

function Get-GitDirty {
    try {
        $status = git status --porcelain 2>$null
        if ($LASTEXITCODE -eq 0 -and $status) { return $true }
    } catch { }
    return $false
}

function Read-Version {
    if (-not (Test-Path $VersionFile)) {
        return @{ Major = 0; Minor = 1; Patch = 0; Build = 0 }
    }

    $content = Get-Content $VersionFile -Raw
    $major = 0; $minor = 1; $patch = 0; $build = 0

    if ($content -match 'PHOENIX_VERSION_MAJOR\s+(\d+)') { $major = [int]$matches[1] }
    if ($content -match 'PHOENIX_VERSION_MINOR\s+(\d+)') { $minor = [int]$matches[1] }
    if ($content -match 'PHOENIX_VERSION_PATCH\s+(\d+)') { $patch = [int]$matches[1] }
    if ($content -match 'PHOENIX_VERSION_BUILD\s+(\d+)') { $build = [int]$matches[1] }

    return @{ Major = $major; Minor = $minor; Patch = $patch; Build = $build }
}

function Write-Version($version, $commit, $dirty) {
    $dirtyFlag = if ($dirty) { "-dirty" } else { "" }
    $versionString = "$($version.Major).$($version.Minor).$($version.Patch)"
    $fullVersion = "$versionString+$($version.Build).$commit$dirtyFlag"

    $content = @"
/**
 * @file version.h
 * @brief Phoenix SDR version information
 *
 * Auto-generated by build.ps1 - DO NOT EDIT MANUALLY
 *
 * Version format: MAJOR.MINOR.PATCH+BUILD.COMMIT[-dirty]
 * Example: 0.2.1+42.a1b2c3d or 0.2.1+42.a1b2c3d-dirty
 */

#ifndef PHOENIX_VERSION_H
#define PHOENIX_VERSION_H

#define PHOENIX_VERSION_MAJOR   $($version.Major)
#define PHOENIX_VERSION_MINOR   $($version.Minor)
#define PHOENIX_VERSION_PATCH   $($version.Patch)
#define PHOENIX_VERSION_BUILD   $($version.Build)
#define PHOENIX_VERSION_STRING  "$versionString"
#define PHOENIX_VERSION_FULL    "$fullVersion"
#define PHOENIX_GIT_COMMIT      "$commit"
#define PHOENIX_GIT_DIRTY       $($dirty.ToString().ToLower())

/* Build timestamp - set by compiler */
#define PHOENIX_BUILD_DATE      __DATE__
#define PHOENIX_BUILD_TIME      __TIME__

#include <stdio.h>

static inline void print_version(const char *tool_name) {
    printf("%s v%s (built %s %s)\n",
           tool_name, PHOENIX_VERSION_FULL,
           PHOENIX_BUILD_DATE, PHOENIX_BUILD_TIME);
}

#endif /* PHOENIX_VERSION_H */
"@

    Set-Content -Path $VersionFile -Value $content -NoNewline
    return $fullVersion
}

function Update-Version {
    $version = Read-Version
    $commit = Get-GitCommit
    $dirty = Get-GitDirty

    # Always increment build number
    $version.Build++

    # Increment version component if requested
    if ($Increment -eq "major") {
        $version.Major++
        $version.Minor = 0
        $version.Patch = 0
        Write-Status "Incrementing MAJOR version"
    }
    elseif ($Increment -eq "minor") {
        $version.Minor++
        $version.Patch = 0
        Write-Status "Incrementing MINOR version"
    }
    elseif ($Increment -eq "patch") {
        $version.Patch++
        Write-Status "Incrementing PATCH version"
    }

    $fullVersion = Write-Version $version $commit $dirty
    Write-Status "Version: $fullVersion"
    return $version
}

#============================================================================
# Build Functions
#============================================================================

function Build-Object($source, $extraFlags) {
    $objName = [System.IO.Path]::GetFileNameWithoutExtension($source)
    $objPath = "$BuildDir\$objName.o"

    Write-Status "Compiling $source..."
    $allFlags = $CFLAGS + $extraFlags
    $allArgs = $allFlags + @("-c", "-o", "`"$objPath`"", "`"$source`"")
    $argString = $allArgs -join " "

    $process = Start-Process -FilePath "`"$CC`"" -ArgumentList $argString -NoNewWindow -Wait -PassThru
    if ($process.ExitCode -ne 0) { throw "Compilation failed for $source" }
    return $objPath
}

#============================================================================
# Main
#============================================================================

try {
    Push-Location $PSScriptRoot
    Write-Status "Using compiler: $CC"

    if ($Clean) {
        Write-Status "Cleaning..."
        if (Test-Path $BuildDir) { Remove-Item -Recurse -Force $BuildDir }
        if (Test-Path $BinDir) { Remove-Item -Recurse -Force $BinDir }
        Write-Status "Clean complete."
        exit 0
    }

    # Update version (increments build number every time)
    $version = Update-Version

    # Set compiler flags
    $CFLAGS = @(
        "-std=c17",
        "-Wall",
        "-Wextra",
        "-pedantic",
        "-I`"$IncludeDir`"",
        "-I`"$SDRplayInclude`""
    )

    if ($Release) {
        $CFLAGS += @("-O2", "-DNDEBUG")
        Write-Status "Release build"
    } else {
        $CFLAGS += @("-O0", "-g", "-D_DEBUG")
        Write-Status "Debug build"
    }

    $LDFLAGS = @(
        "-L`"$SDRplayLib`"",
        "-lsdrplay_api",
        "-lm",
        "-lwinmm"
    )

    # Create directories
    if (-not (Test-Path $BuildDir)) { New-Item -ItemType Directory -Path $BuildDir | Out-Null }
    if (-not (Test-Path $BinDir)) { New-Item -ItemType Directory -Path $BinDir | Out-Null }

    # Build simple_am_receiver
    Write-Status "Building simple_am_receiver..."
    $objects = @(
        (Build-Object "tools\simple_am_receiver.c" @())
    )

    Write-Status "Linking simple_am_receiver.exe..."
    $allArgs = @("-o", "`"$BinDir\simple_am_receiver.exe`"") + $objects + $LDFLAGS
    $argString = $allArgs -join " "
    $process = Start-Process -FilePath "`"$CC`"" -ArgumentList $argString -NoNewWindow -Wait -PassThru
    if ($process.ExitCode -ne 0) { throw "Linking failed" }

    # Copy SDRplay DLL
    $dllSrc = "$SDRplayLib\sdrplay_api.dll"
    $dllDst = "$BinDir\sdrplay_api.dll"
    if ((Test-Path $dllSrc) -and -not (Test-Path $dllDst)) {
        Copy-Item $dllSrc $dllDst
    }
    Write-Status "Built: $BinDir\simple_am_receiver.exe"

    # Build waterfall
    Write-Status "Building waterfall..."

    $kissObj = Build-Object "src\kiss_fft.c" @()
    $waterfallDspObj = Build-Object "tools\waterfall_dsp.c" @()
    $waterfallAudioObj = Build-Object "tools\waterfall_audio.c" @()
    $waterfallObj = Build-Object "tools\waterfall.c" @("-I`"$SDL2Include`"")

    Write-Status "Linking waterfall.exe..."
    $waterfallLdflags = @(
        "-L`"$SDL2Lib`"",
        "-lmingw32",
        "-lSDL2main",
        "-lSDL2",
        "-lm",
        "-lws2_32",
        "-lwinmm"
    )
    $allArgs = @("-o", "`"$BinDir\waterfall.exe`"", "`"$waterfallObj`"", "`"$waterfallDspObj`"", "`"$waterfallAudioObj`"", "`"$kissObj`"") + $waterfallLdflags
    $argString = $allArgs -join " "
    $process = Start-Process -FilePath "`"$CC`"" -ArgumentList $argString -NoNewWindow -Wait -PassThru
    if ($process.ExitCode -ne 0) { throw "Linking failed for waterfall" }

    # Copy SDL2 DLL
    $sdl2DllSrc = "$SDL2Dir\bin\SDL2.dll"
    $sdl2DllDst = "$BinDir\SDL2.dll"
    if ((Test-Path $sdl2DllSrc) -and -not (Test-Path $sdl2DllDst)) {
        Copy-Item $sdl2DllSrc $sdl2DllDst
    }
    Write-Status "Built: $BinDir\waterfall.exe"

    # Build wormhole (M110A constellation display)
    Write-Status "Building wormhole..."

    $wormholeObj = Build-Object "tools\wormhole.c" @("-I`"$SDL2Include`"")

    Write-Status "Linking wormhole.exe..."
    $wormholeLdflags = @(
        "-L`"$SDL2Lib`"",
        "-lmingw32",
        "-lSDL2main",
        "-lSDL2",
        "-lm"
    )
    $allArgs = @("-o", "`"$BinDir\wormhole.exe`"", "`"$wormholeObj`"") + $wormholeLdflags
    $argString = $allArgs -join " "
    $process = Start-Process -FilePath "`"$CC`"" -ArgumentList $argString -NoNewWindow -Wait -PassThru
    if ($process.ExitCode -ne 0) { throw "Linking failed for wormhole" }
    Write-Status "Built: $BinDir\wormhole.exe"

    # Build test_tcp_commands (TCP command parser unit tests)
    Write-Status "Building test_tcp_commands..."

    $tcpCmdObj = Build-Object "src\tcp_commands.c" @()
    $testTcpObj = Build-Object "test\test_tcp_commands.c" @()
    $sdrStubsObj = Build-Object "test\sdr_stubs.c" @()

    Write-Status "Linking test_tcp_commands.exe..."
    $testLdflags = @("-lm")
    $allArgs = @("-o", "`"$BinDir\test_tcp_commands.exe`"", "`"$testTcpObj`"", "`"$tcpCmdObj`"", "`"$sdrStubsObj`"") + $testLdflags
    $argString = $allArgs -join " "
    $process = Start-Process -FilePath "`"$CC`"" -ArgumentList $argString -NoNewWindow -Wait -PassThru
    if ($process.ExitCode -ne 0) { throw "Linking failed for test_tcp_commands" }
    Write-Status "Built: $BinDir\test_tcp_commands.exe"

    # Build SDR source files for sdr_server
    Write-Status "Building SDR library objects..."
    $sdrStreamObj = Build-Object "src\sdr_stream.c" @()
    $sdrDeviceObj = Build-Object "src\sdr_device.c" @()

    # Build sdr_server (TCP control server with SDR integration)
    Write-Status "Building sdr_server..."

    $sdrServerObj = Build-Object "tools\sdr_server.c" @()
    # Reuse tcpCmdObj from above

    Write-Status "Linking sdr_server.exe..."
    $serverLdflags = @(
        "-L`"$SDRplayLib`"",
        "-lsdrplay_api",
        "-lws2_32",
        "-lm",
        "-lwinmm"
    )
    $allArgs = @("-o", "`"$BinDir\sdr_server.exe`"", "`"$sdrServerObj`"", "`"$tcpCmdObj`"", "`"$sdrStreamObj`"", "`"$sdrDeviceObj`"") + $serverLdflags
    $argString = $allArgs -join " "
    $process = Start-Process -FilePath "`"$CC`"" -ArgumentList $argString -NoNewWindow -Wait -PassThru
    if ($process.ExitCode -ne 0) { throw "Linking failed for sdr_server" }
    Write-Status "Built: $BinDir\sdr_server.exe"

    Write-Status "Done."
}
catch {
    Write-Host "BUILD FAILED: $_" -ForegroundColor Red
    exit 1
}
finally {
    Pop-Location
}
