# Phoenix SDR - Build Script (MinGW/GCC)
# Builds simple_am_receiver and waterfall tools

param(
    [switch]$Clean,
    [switch]$Release,
    [ValidateSet("major", "minor", "patch")]
    [string]$Increment
)

$ErrorActionPreference = "Stop"

# Configuration
$ProjectName = "phoenix_sdr"
$SrcDir = "src"
$IncludeDir = "include"
$BuildDir = "build"
$BinDir = "bin"
$VersionFile = "$IncludeDir\version.h"

# SDRplay API paths (optional - only needed for SDR tools)
$SDRplayInclude = "C:\Program Files\SDRplay\API\inc"
$SDRplayLib = "C:\Program Files\SDRplay\API\x64"
$SDRplayAvailable = (Test-Path $SDRplayInclude) -and (Test-Path $SDRplayLib)

# SDL2 paths
$SDL2Dir = "$PSScriptRoot\libs\SDL2\SDL2-2.30.9\x86_64-w64-mingw32"
$SDL2Include = "$SDL2Dir\include\SDL2"
$SDL2Lib = "$SDL2Dir\lib"

# Compiler (MinGW/GCC) - MSYS2 setup
$MSYS2BinDir = "C:\msys64\mingw64\bin"
$UseMSYS2 = Test-Path $MSYS2BinDir

if ($UseMSYS2) {
    # MSYS2 detected - add to PATH and use gcc directly
    $env:PATH = "$MSYS2BinDir;$env:PATH"
    $CC = "$MSYS2BinDir\gcc.exe"
    Write-Host "[phoenix_sdr] Using MSYS2 MinGW64 environment" -ForegroundColor Green
} else {
    # Fall back to direct gcc.exe paths
    $possiblePaths = @(
        "$env:LOCALAPPDATA\Microsoft\WinGet\Packages\BrechtSanders.WinLibs.POSIX.UCRT_Microsoft.Winget.Source_8wekyb3d8bbwe\mingw64\bin\gcc.exe",
        "C:\mingw64\bin\gcc.exe",
        "C:\MinGW\bin\gcc.exe",
        "C:\Program Files\mingw-w64\bin\gcc.exe"
    )

    $CC = $null
    foreach ($path in $possiblePaths) {
        if (Test-Path $path) {
            $CC = $path
            break
        }
    }

    # Fall back to PATH
    if (-not $CC) {
        try {
            $gccPath = (Get-Command gcc -ErrorAction Stop).Source
            $CC = $gccPath
        } catch {
            Write-Host "ERROR: GCC compiler not found!" -ForegroundColor Red
            Write-Host "Please install MinGW-w64 via MSYS2 from: https://www.msys2.org" -ForegroundColor Yellow
            Write-Host "Then run: pacman -S mingw-w64-x86_64-toolchain" -ForegroundColor Yellow
            exit 1
        }
    }
}

function Write-Status($msg) {
    Write-Host "[$ProjectName] " -ForegroundColor Cyan -NoNewline
    Write-Host $msg
}

#============================================================================
# Version Management
#============================================================================

function Get-GitCommit {
    try {
        $commit = git rev-parse --short HEAD 2>$null
        if ($LASTEXITCODE -eq 0) { return $commit.Trim() }
    } catch { }
    return "unknown"
}

function Get-GitDirty {
    try {
        $status = git status --porcelain 2>$null
        if ($LASTEXITCODE -eq 0 -and $status) { return $true }
    } catch { }
    return $false
}

function Read-Version {
    if (-not (Test-Path $VersionFile)) {
        return @{ Major = 0; Minor = 1; Patch = 0; Build = 0 }
    }

    $content = Get-Content $VersionFile -Raw
    $major = 0; $minor = 1; $patch = 0; $build = 0

    if ($content -match 'PHOENIX_VERSION_MAJOR\s+(\d+)') { $major = [int]$matches[1] }
    if ($content -match 'PHOENIX_VERSION_MINOR\s+(\d+)') { $minor = [int]$matches[1] }
    if ($content -match 'PHOENIX_VERSION_PATCH\s+(\d+)') { $patch = [int]$matches[1] }
    if ($content -match 'PHOENIX_VERSION_BUILD\s+(\d+)') { $build = [int]$matches[1] }

    return @{ Major = $major; Minor = $minor; Patch = $patch; Build = $build }
}

function Write-Version($version, $commit, $dirty) {
    $dirtyFlag = if ($dirty) { "-dirty" } else { "" }
    $versionString = "$($version.Major).$($version.Minor).$($version.Patch)"
    $fullVersion = "$versionString+$($version.Build).$commit$dirtyFlag"

    $content = @"
/**
 * @file version.h
 * @brief Phoenix SDR version information
 *
 * Auto-generated by build.ps1 - DO NOT EDIT MANUALLY
 *
 * Version format: MAJOR.MINOR.PATCH+BUILD.COMMIT[-dirty]
 * Example: 0.2.1+42.a1b2c3d or 0.2.1+42.a1b2c3d-dirty
 */

#ifndef PHOENIX_VERSION_H
#define PHOENIX_VERSION_H

#define PHOENIX_VERSION_MAJOR   $($version.Major)
#define PHOENIX_VERSION_MINOR   $($version.Minor)
#define PHOENIX_VERSION_PATCH   $($version.Patch)
#define PHOENIX_VERSION_BUILD   $($version.Build)
#define PHOENIX_VERSION_STRING  "$versionString"
#define PHOENIX_VERSION_FULL    "$fullVersion"
#define PHOENIX_GIT_COMMIT      "$commit"
#define PHOENIX_GIT_DIRTY       $($dirty.ToString().ToLower())

/* Build timestamp - set by compiler */
#define PHOENIX_BUILD_DATE      __DATE__
#define PHOENIX_BUILD_TIME      __TIME__

#include <stdio.h>

static inline void print_version(const char *tool_name) {
    printf("%s v%s (built %s %s)\n",
           tool_name, PHOENIX_VERSION_FULL,
           PHOENIX_BUILD_DATE, PHOENIX_BUILD_TIME);
}

#endif /* PHOENIX_VERSION_H */
"@

    Set-Content -Path $VersionFile -Value $content -NoNewline
    return $fullVersion
}

function Update-Version {
    $version = Read-Version
    $commit = Get-GitCommit
    $dirty = Get-GitDirty

    # Always increment build number
    $version.Build++

    # Increment version component if requested
    if ($Increment -eq "major") {
        $version.Major++
        $version.Minor = 0
        $version.Patch = 0
        Write-Status "Incrementing MAJOR version"
    }
    elseif ($Increment -eq "minor") {
        $version.Minor++
        $version.Patch = 0
        Write-Status "Incrementing MINOR version"
    }
    elseif ($Increment -eq "patch") {
        $version.Patch++
        Write-Status "Incrementing PATCH version"
    }

    $fullVersion = Write-Version $version $commit $dirty
    Write-Status "Version: $fullVersion"
    return $version
}

#============================================================================
# Build Functions
#============================================================================

function Build-Object($source, $extraFlags) {
    $objName = [System.IO.Path]::GetFileNameWithoutExtension($source)
    $objPath = "$BuildDir\$objName.o"

    Write-Status "Compiling $source..."
    $allFlags = $CFLAGS + $extraFlags
    $allArgs = $allFlags + @("-c", "-o", $objPath, $source)

    # Run compiler - use Start-Process to avoid PowerShell's stderr-as-error behavior
    $tempOut = [System.IO.Path]::GetTempFileName()
    $tempErr = [System.IO.Path]::GetTempFileName()
    $proc = Start-Process -FilePath $CC -ArgumentList $allArgs -NoNewWindow -Wait -PassThru `
        -RedirectStandardOutput $tempOut -RedirectStandardError $tempErr
    $stdout = Get-Content $tempOut -ErrorAction SilentlyContinue
    $stderr = Get-Content $tempErr -ErrorAction SilentlyContinue
    Remove-Item $tempOut,$tempErr -ErrorAction SilentlyContinue

    # Show warnings from stderr
    if ($stderr -and $proc.ExitCode -eq 0) {
        $stderr | ForEach-Object { Write-Host "  $_" -ForegroundColor Yellow }
    }

    if ($proc.ExitCode -ne 0) {
        Write-Host "Command: $CC $($allArgs -join ' ')" -ForegroundColor Yellow
        Write-Host "Compiler stderr:" -ForegroundColor Red
        if ($stderr) {
            $stderr | ForEach-Object { Write-Host "  $_" -ForegroundColor Red }
        }
        if ($stdout) {
            $stdout | ForEach-Object { Write-Host "  $_" -ForegroundColor Red }
        }
        throw "Compilation failed for $source with exit code $($proc.ExitCode)"
    }
    return $objPath
}

function Link-Executable($outPath, $objects, $extraLDFLAGS) {
    Write-Status "Linking $(Split-Path -Leaf $outPath)..."
    $allArgs = @("-o", $outPath) + $objects + $LDFLAGS + $extraLDFLAGS

    # Run linker - use Start-Process to avoid PowerShell's stderr-as-error behavior
    $tempOut = [System.IO.Path]::GetTempFileName()
    $tempErr = [System.IO.Path]::GetTempFileName()
    $proc = Start-Process -FilePath $CC -ArgumentList $allArgs -NoNewWindow -Wait -PassThru `
        -RedirectStandardOutput $tempOut -RedirectStandardError $tempErr
    $stdout = Get-Content $tempOut -ErrorAction SilentlyContinue
    $stderr = Get-Content $tempErr -ErrorAction SilentlyContinue
    Remove-Item $tempOut,$tempErr -ErrorAction SilentlyContinue

    # Show warnings from stderr
    if ($stderr -and $proc.ExitCode -eq 0) {
        $stderr | ForEach-Object { Write-Host "  $_" -ForegroundColor Yellow }
    }

    if ($proc.ExitCode -ne 0) {
        Write-Host "Command: $CC $($allArgs -join ' ')" -ForegroundColor Yellow
        Write-Host "Linker stderr:" -ForegroundColor Red
        if ($stderr) {
            $stderr | ForEach-Object { Write-Host "  $_" -ForegroundColor Red }
        }
        if ($stdout) {
            $stdout | ForEach-Object { Write-Host "  $_" -ForegroundColor Red }
        }
        throw "Linking failed for $outPath with exit code $($proc.ExitCode)"
    }
    Write-Host "Built: $outPath" -ForegroundColor Green
}

#============================================================================
# Main
#============================================================================

try {
    Push-Location $PSScriptRoot
    Write-Status "Using compiler: $CC"

    if ($Clean) {
        Write-Status "Cleaning..."
        if (Test-Path $BuildDir) { Remove-Item -Recurse -Force $BuildDir }
        if (Test-Path $BinDir) { Remove-Item -Recurse -Force $BinDir }
        Write-Status "Clean complete."
        exit 0
    }

    # Update version (increments build number every time)
    $version = Update-Version

    # Debug: Show library availability
    Write-Host "[DEBUG] SDRplay: Include=$SDRplayInclude Lib=$SDRplayLib Available=$SDRplayAvailable" -ForegroundColor Magenta
    Write-Host "[DEBUG] SDL2: Dir=$SDL2Dir Available=$(Test-Path $SDL2Dir)" -ForegroundColor Magenta

    # Set compiler flags
    $CFLAGS = @(
        "-std=c17",
        "-Wall",
        "-Wextra",
        "-pedantic",
        "-I`"$IncludeDir`"",
        "-I`"$SDRplayInclude`""
    )

    if ($Release) {
        $CFLAGS += @("-O2", "-DNDEBUG")
        Write-Status "Release build"
    } else {
        $CFLAGS += @("-O0", "-g", "-D_DEBUG")
        Write-Status "Debug build"
    }

    $LDFLAGS = @(
        "-L`"$SDRplayLib`"",
        "-lsdrplay_api",
        "-lm",
        "-lwinmm"
    )

    # Create directories
    if (-not (Test-Path $BuildDir)) { New-Item -ItemType Directory -Path $BuildDir | Out-Null }
    if (-not (Test-Path $BinDir)) { New-Item -ItemType Directory -Path $BinDir | Out-Null }

    # Check SDRplay availability
    if (-not $SDRplayAvailable) {
        Write-Host "WARNING: SDRplay API not found - skipping SDR-dependent tools" -ForegroundColor Yellow
        Write-Host "  Install from: https://www.sdrplay.com/api/" -ForegroundColor Yellow
        Write-Host "  Building WWV generator only..." -ForegroundColor Yellow
        Write-Host ""
    }

    # Build simple_am_receiver (requires SDRplay)
    if ($SDRplayAvailable) {
        Write-Status "Building simple_am_receiver..."
        $objects = @(
            (Build-Object "tools\simple_am_receiver.c" @())
        )

        Link-Executable "$BinDir\simple_am_receiver.exe" $objects @()

        # Copy SDRplay DLL
        $dllSrc = "$SDRplayLib\sdrplay_api.dll"
        $dllDst = "$BinDir\sdrplay_api.dll"
        if ((Test-Path $dllSrc) -and -not (Test-Path $dllDst)) {
            Copy-Item $dllSrc $dllDst
        }
        Write-Status "Built: $BinDir\simple_am_receiver.exe"
    }

    # Build waterfall (requires SDRplay and SDL2)
    if ($SDRplayAvailable -and (Test-Path "$SDL2Dir")) {
        Write-Status "Building waterfall..."

    $kissObj = Build-Object "src\kiss_fft.c" @()
    $wwvClockObj = Build-Object "tools\wwv_clock.c" @()
    $tickDetectorObj = Build-Object "tools\tick_detector.c" @()
    $markerDetectorObj = Build-Object "tools\marker_detector.c" @()
    $slowMarkerDetectorObj = Build-Object "tools\slow_marker_detector.c" @()
    $markerCorrelatorObj = Build-Object "tools\marker_correlator.c" @()
    $syncDetectorObj = Build-Object "tools\sync_detector.c" @()
    $toneTrackerObj = Build-Object "tools\tone_tracker.c" @()
    $tickCorrelatorObj = Build-Object "tools\tick_correlator.c" @()
    $subcarrierDetectorObj = Build-Object "tools\subcarrier_detector.c" @()
    $bcdEnvelopeObj = Build-Object "tools\bcd_envelope.c" @()
    $bcdDecoderObj = Build-Object "tools\bcd_decoder.c" @()
    $bcdTimeDetectorObj = Build-Object "tools\bcd_time_detector.c" @()
    $bcdFreqDetectorObj = Build-Object "tools\bcd_freq_detector.c" @()
    $bcdCorrelatorObj = Build-Object "tools\bcd_correlator.c" @()
    $waterfallFlashObj = Build-Object "tools\waterfall_flash.c" @()
    $waterfallDspObj = Build-Object "tools\waterfall_dsp.c" @()
    $waterfallAudioObj = Build-Object "tools\waterfall_audio.c" @()
    $waterfallTelemObj = Build-Object "tools\waterfall_telemetry.c" @()
    $waterfallObj = Build-Object "tools\waterfall.c" @("-I`"$SDL2Include`"")

    Write-Status "Linking waterfall.exe..."
    $waterfallLdflags = @(
        "-L`"$SDL2Lib`"",
        "-lmingw32",
        "-lSDL2main",
        "-lSDL2",
        "-lm",
        "-lws2_32",
        "-lwinmm"
    )
    $allArgs = @("-o", "`"$BinDir\waterfall.exe`"", "`"$waterfallObj`"", "`"$tickDetectorObj`"", "`"$markerDetectorObj`"", "`"$slowMarkerDetectorObj`"", "`"$markerCorrelatorObj`"", "`"$syncDetectorObj`"", "`"$toneTrackerObj`"", "`"$tickCorrelatorObj`"", "`"$subcarrierDetectorObj`"", "`"$bcdEnvelopeObj`"", "`"$bcdDecoderObj`"", "`"$bcdTimeDetectorObj`"", "`"$bcdFreqDetectorObj`"", "`"$bcdCorrelatorObj`"", "`"$waterfallFlashObj`"", "`"$wwvClockObj`"", "`"$waterfallDspObj`"", "`"$waterfallAudioObj`"", "`"$waterfallTelemObj`"", "`"$kissObj`"") + $waterfallLdflags
    $argString = $allArgs -join " "
    $process = Start-Process -FilePath "`"$CC`"" -ArgumentList $argString -NoNewWindow -Wait -PassThru
    if ($process.ExitCode -ne 0) { throw "Linking failed for waterfall" }

    # Copy SDL2 DLL
        $sdl2DllSrc = "$SDL2Dir\bin\SDL2.dll"
        $sdl2DllDst = "$BinDir\SDL2.dll"
        if ((Test-Path $sdl2DllSrc) -and -not (Test-Path $sdl2DllDst)) {
            Copy-Item $sdl2DllSrc $sdl2DllDst
        }
        Write-Status "Built: $BinDir\waterfall.exe"
    }

    # Build wormhole (M110A constellation display) - requires SDL2
    if (Test-Path "$SDL2Dir") {
        Write-Status "Building wormhole..."

    $wormholeObj = Build-Object "tools\wormhole.c" @("-I`"$SDL2Include`"")

    Write-Status "Linking wormhole.exe..."
    $wormholeLdflags = @(
        "-L`"$SDL2Lib`"",
        "-lmingw32",
        "-lSDL2main",
        "-lSDL2",
        "-lm"
    )
    $allArgs = @("-o", "`"$BinDir\wormhole.exe`"", "`"$wormholeObj`"") + $wormholeLdflags
    $argString = $allArgs -join " "
        $process = Start-Process -FilePath "`"$CC`"" -ArgumentList $argString -NoNewWindow -Wait -PassThru
        if ($process.ExitCode -ne 0) { throw "Linking failed for wormhole" }
        Write-Status "Built: $BinDir\wormhole.exe"
    }

    # Build test_tcp_commands (TCP command parser unit tests)
    Write-Status "Building test_tcp_commands..."

    $tcpCmdObj = Build-Object "src\tcp_commands.c" @()
    $testTcpObj = Build-Object "test\test_tcp_commands.c" @()
    $sdrStubsObj = Build-Object "test\sdr_stubs.c" @()

    Write-Status "Linking test_tcp_commands.exe..."
    $testLdflags = @("-lm")
    $allArgs = @("-o", "`"$BinDir\test_tcp_commands.exe`"", "`"$testTcpObj`"", "`"$tcpCmdObj`"", "`"$sdrStubsObj`"") + $testLdflags
    $argString = $allArgs -join " "
    $process = Start-Process -FilePath "`"$CC`"" -ArgumentList $argString -NoNewWindow -Wait -PassThru
    if ($process.ExitCode -ne 0) { throw "Linking failed for test_tcp_commands" }
    Write-Status "Built: $BinDir\test_tcp_commands.exe"

    # Build test_telemetry (UDP telemetry unit tests)
    Write-Status "Building test_telemetry..."

    $telemObj = Build-Object "tools\waterfall_telemetry.c" @()
    $testTelemObj = Build-Object "test\test_telemetry.c" @()

    Write-Status "Linking test_telemetry.exe..."
    $telemLdflags = @("-lws2_32", "-lm")
    $allArgs = @("-o", "`"$BinDir\test_telemetry.exe`"", "`"$testTelemObj`"", "`"$telemObj`"") + $telemLdflags
    $argString = $allArgs -join " "
    $process = Start-Process -FilePath "`"$CC`"" -ArgumentList $argString -NoNewWindow -Wait -PassThru
    if ($process.ExitCode -ne 0) { throw "Linking failed for test_telemetry" }
    Write-Status "Built: $BinDir\test_telemetry.exe"

    # Build SDR source files for sdr_server
    Write-Status "Building SDR library objects..."
    $sdrStreamObj = Build-Object "src\sdr_stream.c" @()
    $sdrDeviceObj = Build-Object "src\sdr_device.c" @()

    # Build sdr_server (TCP control server with SDR integration)
    Write-Status "Building sdr_server..."

    $sdrServerObj = Build-Object "tools\sdr_server.c" @()
    # Reuse tcpCmdObj from above

    $serverLdflags = @(
        "-L`"$SDRplayLib`"",
        "-lsdrplay_api",
        "-lws2_32",
        "-lm",
        "-lwinmm"
    )
    $serverObjects = @($sdrServerObj, $tcpCmdObj, $sdrStreamObj, $sdrDeviceObj)
    Link-Executable "$BinDir\sdr_server.exe" $serverObjects $serverLdflags

    #===== WWV Test Signal Generator (no SDR dependencies) =====
    Write-Status "Building wwv_gen..."
    # Build IQ recorder objects (needed for .iqr file output)
    $iqrMetaObj = Build-Object "src\iqr_meta.c" @()
    $iqrObj = Build-Object "src\iq_recorder.c" @()

    # Build WWV signal generator components
    $oscillatorObj = Build-Object "tools\oscillator.c" @()
    $bcdEncoderObj = Build-Object "tools\bcd_encoder.c" @()
    $wwvSignalObj = Build-Object "tools\wwv_signal.c" @()
    $wwvGenObj = Build-Object "tools\wwv_gen.c" @()

    $wwvObjects = @($wwvGenObj, $wwvSignalObj, $oscillatorObj, $bcdEncoderObj, $iqrObj, $iqrMetaObj)
    Link-Executable "$BinDir\wwv_gen.exe" $wwvObjects @("-lm")

    Write-Status "Done."
}
catch {
    Write-Host "BUILD FAILED: $_" -ForegroundColor Red
    exit 1
}
finally {
    Pop-Location
}
