/**
 * @file version.h
 * @brief Phoenix SDR version information
 *
 * Auto-generated by build.ps1 - DO NOT EDIT MANUALLY
 *
 * Version format: MAJOR.MINOR.PATCH+BUILD.COMMIT[-dirty]
 * Example: 0.2.1+42.a1b2c3d or 0.2.1+42.a1b2c3d-dirty
 */

#ifndef PHOENIX_VERSION_H
#define PHOENIX_VERSION_H

#define PHOENIX_VERSION_MAJOR   0
#define PHOENIX_VERSION_MINOR   3
#define PHOENIX_VERSION_PATCH   0
#define PHOENIX_VERSION_BUILD   57
#define PHOENIX_VERSION_STRING  "0.3.0"
#define PHOENIX_VERSION_FULL    "0.3.0+57.b29b363-dirty"
#define PHOENIX_GIT_COMMIT      "b29b363"
#define PHOENIX_GIT_DIRTY       true

/* Build timestamp - set by compiler */
#define PHOENIX_BUILD_DATE      __DATE__
#define PHOENIX_BUILD_TIME      __TIME__

#include <stdio.h>

static inline void print_version(const char *tool_name) {
    printf("%s v%s (built %s %s)\n",
           tool_name, PHOENIX_VERSION_FULL,
           PHOENIX_BUILD_DATE, PHOENIX_BUILD_TIME);
}

#endif /* PHOENIX_VERSION_H */